name: Test Differential Privacy Lab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r 1-differential-privacy-lab/requirements.txt
        pip install pytest nbconvert nbformat jupyter

    - name: Run Unit Tests
      run: |
        if [ -d "lib" ]; then
          pytest lib/
        fi

    - name: Execute Notebooks
      run: |
        for notebook in 1-differential-privacy-lab/notebooks/*.ipynb; do
          jupyter nbconvert --to notebook --execute "$notebook" --inplace --ExecutePreprocessor.timeout=600
        done

